"""
Chain 2 — Discovery
===================
Executes the YouTube queries generated by Chain 1 against the YouTube Data API.
Extracts unique channels, builds their rich profiles, and applies basic tier filtering.
"""

import asyncio
import logging
from typing import List, Dict

from chain_0_ICP import ICPProfile
from chain_1_keywordExpansion import ExpandedKeywordSet

import sys
import os
from dotenv import load_dotenv

# Ensure backend is in the path for module resolution
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Load environment variables before importing services that use them globally
load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

from services.platforms.youtube import youtube_search, build_channel_profile

logger = logging.getLogger(__name__)

async def run_discovery(icp: ICPProfile, keywords: ExpandedKeywordSet) -> List[Dict]:
    """
    Executes the discovery phase for YouTube.
    1. Runs all queries concurrently.
    2. Extracts and deduplicates channel IDs.
    3. Builds channel profiles concurrently.
    4. Applies basic follower constraints based on the ICP.
    """
    logger.info("Starting Chain 2: Discovery (YouTube)")

    # 1. Run all YouTube queries concurrently
    search_tasks = []
    for q in keywords.youtube_queries:
        search_tasks.append(
            youtube_search(
                query=q.query,
                max_results=q.max_results,
                search_type=q.search_type,
                region_code=q.region_code,
                relevance_language=q.relevance_language
            )
        )
    
    logger.info(f"Executing {len(search_tasks)} YouTube search queries...")
    search_results = await asyncio.gather(*search_tasks, return_exceptions=True)

    # 2. Extract and deduplicate Channel IDs
    unique_channel_ids = set()
    for items in search_results:
        if isinstance(items, Exception):
            logger.error(f"Search query failed: {items}")
            continue
            
        for item in items:
            # The structure depends on the search type
            # For "channel", ID is in item["id"]["channelId"]
            # For "video", ID is in item["snippet"]["channelId"]
            
            cid = None
            if item.get("id", {}).get("kind") == "youtube#channel":
                cid = item.get("id", {}).get("channelId")
            elif item.get("id", {}).get("kind") == "youtube#video":
                cid = item.get("snippet", {}).get("channelId")
                
            if cid:
                unique_channel_ids.add(cid)

    logger.info(f"Discovered {len(unique_channel_ids)} unique YouTube channels.")

    if not unique_channel_ids:
        logger.warning("No channels discovered.")
        return []

    # 3. Build full profiles for all unique channels concurrently
    logger.info("Building full channel profiles (this may take a moment)...")
    profile_tasks = [build_channel_profile(cid) for cid in unique_channel_ids]
    raw_profiles = await asyncio.gather(*profile_tasks, return_exceptions=True)

    # 4. Clean up candidates (Filtering removed as requested)
    candidates = []
    
    for p in raw_profiles:
        if isinstance(p, Exception):
            logger.error(f"Failed to build profile: {p}")
            continue
        if not p:
            continue
            
        candidates.append(p)
            
    logger.info(f"Discovery complete: Returning {len(candidates)} channels (no tier filtering applied).")
    
    return candidates


# ─────────────────────────────────────────────
# QUICK LOCAL TEST
# ─────────────────────────────────────────────
if __name__ == "__main__":
    import json
    
    from chain_0_ICP import BrandBrief, CampaignGoal, Platform, FollowerTier, run_icp_chain
    from chain_1_keywordExpansion import run_keyword_expansion
    
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    sample_brief = BrandBrief(
        brand_name         = "Dot & Key",
        product_description= "Vitamin C serum for hyperpigmentation targeting Indian women",
        campaign_goal      = CampaignGoal.CONVERSION,
        niche              = "skincare",
        platforms          = [Platform.YOUTUBE],
        follower_tier      = FollowerTier.MICRO,
        target_audience    = "Indian women 22-35, interested in clean beauty",
        audience_location  = "India",
        audience_age_range = "22-35",
        language           = "English and Hindi",
        competitor_brands  = ["Minimalist", "Plum"],
        excluded_niches    = ["adult content", "alcohol"],
    )

    async def main():
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            print("ERROR: GROQ_API_KEY not found in environment.")
            return

        print("=== RUNNING CHAIN 0 (ICP) ===")
        icp = await run_icp_chain(sample_brief, api_key)
        
        print("\n=== RUNNING CHAIN 1 (Keyword Expansion) ===")
        keywords = run_keyword_expansion(icp)
        print(f"Generated {len(keywords.youtube_queries)} YouTube queries.")
        
        # We limit the number of queries for this test to save quota and time
        # You can remove this slice to run the full discovery
        keywords.youtube_queries = keywords.youtube_queries[:2]
        print(f"Limiting to {len(keywords.youtube_queries)} queries for quick local test.")
        
        print("\n=== RUNNING CHAIN 2 (Discovery) ===")
        candidates = await run_discovery(icp, keywords)
        
        print("\n=== RESULTS ===")
        if not candidates:
            print("No candidates matched the criteria.")
        else:
            print(f"Found {len(candidates)} candidates.")
            for c in candidates:
                print(f"\n- {c['channel_title']} ({c['profile_url']})")
                print(f"  Followers: {c['followers']:,}")
                print(f"  Avg Views: {c['avg_views']:,} | ER: {c['engagement_rate']}%")
                if "recent_videos" in c and c["recent_videos"]:
                    print(f"  Recent Videos: {len(c['recent_videos'])} analyzed.")
                    for v in c["recent_videos"][:2]:
                        print(f"    * ID: {v['video_id']} | Views: {v['views']:,} | Likes: {v['likes']:,}")
                    if len(c["recent_videos"]) > 2:
                        print(f"    * ...and {len(c['recent_videos']) - 2} more.")

    asyncio.run(main())
